name = "DynamicSparseArrays"
uuid = "8086fd22-9a0c-46a5-a6c8-6e24676501fe"
authors = ["Guillaume Marques <guillaume.marques@protonmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
